mappings:
  axes:
    - axes[1]
    - axes[0]
    - axes[3]
    - axes[4]
    - axes[5]
    - axes[6]
    - axes[7]

  buttons:
    - buttons[0]
    - buttons[3]
    - buttons[2]
    - buttons[1]
    - buttons[4]
    - buttons[5]
    - buttons[6]
