mappings:
  axes:
    - axes[1]
    - axes[0]
    - axes[2]
    - axes[3]
    - axes[4]
    - axes[5]
    - -1*axes[6]
    - axes[7]

  buttons:
    - buttons[0]
    - buttons[1]
    - buttons[2]
    - buttons[3]
    - buttons[4]
    - buttons[5]
    - buttons[6]
    - buttons[7]
    - buttons[8]

operation_cmds:
        - motion_mode
        - Vx
        - Vy
        - Rz
        - gait
        - gait_duration
        - gait_frequency_cmd
        - feetswing_height_cmd
        - body_height_cmd
        - body_roll
        - body_pitch
        - stance_width_cmd
        - stance_length_cmd

